### ISSUE TITLE
Pattern case insensitivity

### ISSUE THREAD

**Issue by robouk** [christiangalsterer/stash-filehooks-plugin#10]
Can't figure out the pattern expression as it does not appear to be standard regex.

I would expect pattern `/\.(mp3|mp4)/gi` to affect the following filetypes:
- .mp3
- .MP3
- .Mp3
- .mP3
- .mp4
- .MP4
- .Mp4
- .mP4

The pattern only affects `.mp3` and `.mp4`.  How would a user create a case insensitive pattern?

**Comment by christiangalsterer** [comment]
The following expression should work:
.*(?i)(mp3|mp4)$

(?i) makes the expression on the right hand side case insensitive.
