### ISSUE TITLE
Do not reject push with big file deletions

### ISSUE THREAD

**Issue by merryech0** [christiangalsterer/stash-filehooks-plugin#11]
```
dd if=/dev/zero of=big.file bs=1024k count=1 # creating "big" file
git add big.file
git commit -m "+ big.file"
git push
# enable hook with limit 1024 bytes
git rm big.file
git commit -m "- big.file"
git push
```

remote: =================================
remote: File [big.file] is too large. Maximum allowed file size is 1024 bytes
remote: =================================
To ssh://git@git.example.com:7999/test/test.git
 ! [remote rejected] master -> master (pre-receive hook declined)

**Comment by christiangalsterer** [comment]
I'll will look into this in the next days.

**Comment by christiangalsterer** [comment]
@ekho Which version of the plugin and Bitbucket Server (Stash) are you using. Normally "delete" changes are not considered for the plugin.

**Comment by merryech0** [comment]
Latest available at marketplace - 2.1.1
![_051](https://cloud.githubusercontent.com/assets/374426/12442679/0cc76a1c-bf63-11e5-8e48-ee5e69bc2a3a.png)

**Comment by christiangalsterer** [comment]
I found the bug and will try to provide a fix in the next days.

**Comment by christiangalsterer** [comment]
A new release 2.1.2 is available fixing this issue.

**Comment by merryech0** [comment]
Thank you!
