### ISSUE TITLE
Can't roll back a commit with a force push

### ISSUE THREAD

**Issue by ar613** [christiangalsterer/stash-filehooks-plugin#14]
I tried to do a git push --force after rolling back the last commit and got this error:

remote: Hook org.christiangalsterer.stash.filehooks.plugin.hook.FileSizeHook failed. Error:
remote: At least one commit ID must be provided to retrieve changesets
To ssh://git@dev.com:7999/test/mergetest.git
! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@dev.com:7999/test/mergetest.git'

**Comment by christiangalsterer** [comment]
You you pls. add the sequence of git commands with parameters you executed to commit/rollback/commit/push.

**Comment by ar613** [comment]
git commit -m"Test"
git push
git reset --hard 15ecf1d0422  (the previous commit to the one i just did)
git push --force

**Comment by antoanelenkov** [comment]
Any solution?

**Comment by christiangalsterer** [comment]
I try to look into it the next days.
Which plugin and Bitbucket version do you use?

**Comment by ar613** [comment]
Bitbucket v4.8.3
File Hooks Plugin Version: 2.3.0

**Comment by christiangalsterer** [comment]
New plugin version 2.3.1 is released to the Atlasssian Marketplace. Thanks again for providing a pull request.
