### ISSUE TITLE
Passing integer to file size hook via rest api fails with java.lang.ClassCastException

### ISSUE THREAD

**Issue by kbrnsr** [christiangalsterer/stash-filehooks-plugin#19]
Using python and Bitbucket Server 4.2.0 (see [exception log](https://github.com/christiangalsterer/stash-filehooks-plugin/files/341809/exception.txt) for more info)

I tried passing the following dict (gets converted to JSON) to the generic "enable" endpoint for hooks:

``` python
{u'pattern-1': u'.*',
u'size-1': 100000,
u'pattern-exclude-1': '',
u'pattern-branches-1': ''}
```

The problem is that "size-1" is an integer and not a string which makes the validation fail, the logs indicate that [line 46 in FileSizeHookValidator.java](https://github.com/christiangalsterer/stash-filehooks-plugin/blob/master/src/main/java/org/christiangalsterer/stash/filehooks/plugin/hook/FileSizeHookValidator.java#L46) is the problem:

``` java
try {
    int size = Integer.parseInt(settings.getString(SETTINGS_SIZE_PREFIX + i, ""));
    if (size < 1) {
        errors.addFieldError("size-" + i, i18n.getText("filesize-hook.error.size", "Size must be an integer value larger than 0"));
    }
} catch (NumberFormatException e) {
    errors.addFieldError(SETTINGS_SIZE_PREFIX + i, i18n.getText("filesize-hook.error.size", "Size must be an integer value larger than 0"));
}
```

**Comment by christiangalsterer** [comment]
Can you please try to use a string for the size instead of an int, like in the following example?

```
{u'pattern-1': u'.*',
u'size-1': '100000',
u'pattern-exclude-1': '',
u'pattern-branches-1': ''}
```

I think it should work then.

**Comment by kbrnsr** [comment]
I've already fixed the problem by converting the parameter to string, but the plugin should give some kind of error message if the exception occurs instead of getting a 5xx error (this is the acual issue) from the rest api
