### ISSUE TITLE
Implement MergeRequestCheck on the FileHooks plugin

### ISSUE THREAD

**Issue by ellaz** [christiangalsterer/stash-filehooks-plugin#20]
Hi, I have implemented a MergeRequestCheck - The original plugin did not allow a hook on a merge request from a repository without hook settings to one with.
I would like to create a pull request with my changes, but do not have permissions. How can I do that?
Branch name- MergeRequestCheck

**Comment by christiangalsterer** [comment]
Hi,
please use the usual Github flow and create a clone of my repo, make your changes on a new branch on the fork repo and when done please create a PR between the branch on the fork repo and master of this repo.

**Comment by ellaz** [comment]
Sorry about that, it's the first time I'm using Github, I've created a pull request

**Comment by christiangalsterer** [comment]
Implemented and released for File Name Hook in version 2.4.0. File Size Hook is open.

**Comment by ellaz** [comment]
Thank you!
