### ISSUE TITLE
Rejects pushes of new branches when they contain a large file in a previous commit

### ISSUE THREAD

**Issue by itay** [christiangalsterer/stash-filehooks-plugin#3]
If I have a branch that in the past had a commit with a large file in it, and I create a new branch where that commit is in the history, a subsequent push will fail. This is because the plugin checks all commits since the beginning of time.

**Comment by christiangalsterer** [comment]
This was the original intention of the hook, to prevent such commits at all. But I understand that this might be a problem for an existing code base. Need to see if I can make this configurable.

**Comment by itay** [comment]
Yeah, I totally get it, I'm just running into an "in the wild" repo :)

I think one question is what the desired behavior is. The problem is that Stash won't tell you what the original branching point of the branch is (i.e. where it was created from), and thus you don't know which commit to check.

One possibility is to simply say not to verify new branches. Maybe another option is to find out which branches contain each commit, and as soon as you hit a commit which is in another branch, stop.

**Comment by rogueluke** [comment]
this seems to happen for tags as well

**Comment by mkgl** [comment]
vote :)

**Comment by christiangalsterer** [comment]
I was on vacation and just returned. I will first concentrate on making the plugin compatible with Bitbucket 4.x (#5). After that I will look into this improvement.

**Comment by christiangalsterer** [comment]
Here some updates:
Tags: Here I think I will exclude them completely
Branches: I checked on the bitbucket API but I'm not clear yet how to detect the branch point and limit the number of commits to check, see also #2. It somebody has an idea, pls. share.

**Comment by rplzzz** [comment]
I've recently encountered this problem too (i.e., "bad" files in the project's deep history blocking new branch pushes).  I believe the API class you need to limit the range of commits is `CommitsBetweenRequest`:  
https://developer.atlassian.com/static/javadoc/bitbucket-server/4.3.1/api/reference/com/atlassian/bitbucket/commit/CommitsBetweenRequest.html

I think that in most cases it would be sufficient to check the commits between the default branch and the branch being pushed.  Technically this could fail on an edge case where you branched from a branch that wasn't the default branch, and the offending files were on the old branch, but not the new branch.  However, I imagine that would be a rare case.

Hope that helps.

**Comment by tarnowsc** [comment]
If you want to get rid of your embarrassing git history you could use:
https://rtyley.github.io/bfg-repo-cleaner/

This will reduce .git folder size and decrease time to create new branch

**Comment by christiangalsterer** [comment]
Closing this now as this is also covered with #1
