### ISSUE TITLE
instructions for compiling latest version

### ISSUE THREAD

**Issue by flare04** [christiangalsterer/stash-filehooks-plugin#30]
Hi, I'm trying to build this plugin for bitbucket. If I run atlas-run it downloads a heap of stuff but nothing happens when I get to the local site.

I need to add it as we need the latest fix. So any instructions on building it would be great.

Thanks

**Comment by christiangalsterer** [comment]
Please see https://community.atlassian.com/t5/Bitbucket-questions/Atlas-run-no-longer-works-with-Bitbucket-Server-5-0-0/qaq-p/584083
