### ISSUE TITLE
File Name Hook is not listed in the "Pre receive" hooks

### ISSUE THREAD

**Issue by syee514** [christiangalsterer/stash-filehooks-plugin#32]
The File Name Hook is not listed in the repository's "Pre receive" hooks in the following environment:
* Bitbucket Server v5.2.2 and v5.4.1
* File Hooks Plugin v3.0.0

**Comment by syee514** [comment]
The File Name Hook is listed in "Merge checks" and not "Pre receive" hooks. Can you please update the documentation to state the File Name Hook location.

Thank-you!

**Comment by christiangalsterer** [comment]
Thanks for reporting this, need to check what is wrong here.

**Comment by christiangalsterer** [comment]
Reason is that the File Name Hook also check for merge commits and BB has changed the behaviour where a hook is added when it implements different hook extension interfaces.

**Comment by christiangalsterer** [comment]
Updated documentation and new version 3.2.0 released to Atlassian Marketplace.
