### ISSUE TITLE
File hook should be available at Project level

### ISSUE THREAD

**Issue by eeijlar** [christiangalsterer/stash-filehooks-plugin#35]
From an administration point of view it would be better if the filehooks plugin was available at the project level in Bit Bucket rather than at the repository level.

When project administrators create new repositories they have to remember to enable the file hook plugin, whereas if it was enabled at project level the settings would be inherited from the project.

There are two plugins in Bit Bucket provided by Atlassian which work at the project level: Verify Committer and Reject Force Push

**Comment by christiangalsterer** [comment]
With later versions of Bitbucket this is supported I had anyways to support this in the next version.

**Comment by eeijlar** [comment]
That would be great 👍

**Comment by christiangalsterer** [comment]
Fixed in 3.1.0 which is available now in the Atlassian Marketplace. Please note that the UI is functional but needs some rework which will be done in one of the next versions, see also #36.

**Comment by eeijlar** [comment]
Wow that was quick! Great - look forward to using it.
