### ISSUE TITLE
File Name Hook missing in configuration of repo

### ISSUE THREAD

**Issue by AndreasStutz** [christiangalsterer/stash-filehooks-plugin#45]
No problem but info: File Name Hook is available elsewhere now in BB Version 5.9.1 (maybe earlier, too): See section "Pull Requests" menu item "Merge Checks".

**Comment by christiangalsterer** [comment]
Yes, see already updated documentation in the [README.md](https://github.com/christiangalsterer/stash-filehooks-plugin/blob/master/README.md) file.
