### ISSUE TITLE
Don't reject tags?

### ISSUE THREAD

**Issue by jsmarsch** [christiangalsterer/stash-filehooks-plugin#7]
So I have a git repo where there used to be some large .bak files.  No current commits should point to them, but when we do a 

git tag -a tagname
git push origin tagname

the filesize hook blocks tag commit based upon size.

I could work around this if there were a way to exclude specific files from the size filter (there are only 3), but my attempts to do so have failed.

**Comment by christiangalsterer** [comment]
There is another request open to be able to exclude tags completely (#3), which should solve your problem.
In addition I think to add an option to also to allow to specify an exclude pattern.

**Comment by christiangalsterer** [comment]
Added an option in version 2.1.0 to specify exclude patterns, see #8. Hope to find some time in the next days to exclude tags completely from checks.

**Comment by christiangalsterer** [comment]
Bug fix release 2.1.1 available as 2.1.0 was incomplete

**Comment by jsmarsch** [comment]
Nice!  Excluding tags would still be a great addition.

**Comment by christiangalsterer** [comment]
I finally had some time and tags are now excluded from checks starting with version 2.2.0, which was just released to the Atlasssian Marketplace.
